### ISSUE TITLE
[FEATURE] AlarmList

### ISSUE THREAD

**Issue by suhyun113** [HICURE/HICURE#10]
### 작업 사항💡

메인 하단바에서 알람 버튼 클릭 시 이동하는 페이지로, 알람 목록 페이지를 구현할 것입니다. 총 알람은 3개로 고정되며, 기본 세팅을 사용자가 변경할 수 있도록 합니다.

### Todo

- [x] 알람 제목 생성
- [x] 알람 목록 생성
- [x] 각 알람 색상 및 디자인 적용
