### ISSUE TITLE
[FEATURE] Navigation Bar

### ISSUE THREAD

**Issue by phy-ju** [HICURE/HICURE#13]
### 작업 사항💡

각 화면에 들어갈 네비게이션 바를 구현할 것 입니다. 총 4가지로 Home/Alarm/Serve/User 순으로 나열하고 있습니다

### Todo

- [ ] 각 아이콘 크기 조정
- [ ] 네비게이션 바 높이 조정
- [ ] 화면 전환 코드 작성
- [ ] 몇몇 화면 연결하여 테스트
