### ISSUE TITLE
[FEATURE] TitleBar

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#20]
### 작업 사항💡

앱을 사용하면서 기본적으로 있는 타이틀바 만들기

> 타이틀바 : 아래 화면에 있는 "오늘의 폐건강", "폐활량 꿀팁" 부분
<img src="https://github.com/user-attachments/assets/e6bf84ab-a38b-4490-9604-aec6aa24f2da" width=250>
<img src="https://github.com/user-attachments/assets/669d0e7f-ae65-46fb-9838-c6be70551845" width=250>

### Todo

- [x] 상단바 디자인하기
- [x] 화면마다 상단바 띄우기
- [x] 화면에 맞는 상단바 내용 띄우기
- [x] 글씨 크기에 맞춰서 뒤에 도형 너비 바꾸기

### 기타사항

Base Activity를 건들이면 된다고 하는데...
그거까지 건들이기엔 너무 들어가는 것 같아서 그냥 Activity마다
xml이랑 kotlin코드를 추가하는 것으로 결정
