### ISSUE TITLE
[FEATURE] Check Id

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#25]
### 작업 사항💡

최초 1회 접속할 때 뜨는 화면 중, 해당 어플을 사용하기 위해 필요한 식별 코드화면을 디자인 할 예정

### Todo
<img src="https://github.com/user-attachments/assets/b0781c29-6c0d-4641-8508-d97dad719dcd" width=250>
<img src="https://github.com/user-attachments/assets/b3503260-9f99-4eca-bfc3-bbe18df48ac4" width=250>

Design
---
- [x] ~배경 물결 넣기~ ( 보류 )
- [x] 팝업창 디자인하기
- [x] 확인 버튼 누르면 메인 엑티비티로 이동

Feature
---
- [x] 식별코드 인증이 작동되도록 만들기

### 기타사항

현재 상황
---
<img src="https://github.com/user-attachments/assets/27054048-ed48-4f66-ba31-24f89857509e" width=250>

- 고민 중인게... 뒤에 물결을 넣지 말까 싶기도 합니다.
- 피그마 디자인이랑 똑같이 팝업 너비를 고정시키는게 좋을까?

최초 1회 할 수 있도록, 식별코드는 대략 30개 정도 만들어두기
