### ISSUE TITLE
[FEATURE] Initial Survey

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#29]
### 작업 사항💡

최초 1회 실시하는 간단한 진단평가입니다.

연구팀에서 질문하길 원하는 문항이 순서대로 들어가며, 그것을 예, 아니오 또는 문장으로 입력할 수 있도록 합니다.
모든 설문이 체크되었다면, 해당 내용을 기록하고, 확인을 터치했을 때, 메인 화면으로 가게됩니다.

### Todo

Design
---

<img src="https://github.com/user-attachments/assets/1294cfd2-d2ce-4184-a8c4-427cadb46641" width=250>

- [x] 예 아니오 문항 만들기 ( 예, 아니오 )
- [x] ~선택 문항 만들기 ( 1 ~ 5 체크 )~
- [x] 문장 입력 문항 만들기 ( 키보드 입력 )

Programming
---
- [x] 문항의 필수 여부가 나타나져 있어야 한다.
- [x] 필수 문항을 체크하지 않을 시 확인 버튼을 눌러도 다음 페이지로 넘어가지 않는다.
- [x] 확인 버튼 >> 클릭한 결과 저장, 메인 화면 이동

### 기타사항

해당 디자인은 이후에 만족도 조사에서도 다시 사용할 템플릿이기 때문에, 동적으로 변동 가능하게 만들어야 한다는 거 생각하면서 만들기
