### ISSUE TITLE
[FEATURE] SetAlarm

### ISSUE THREAD

**Issue by suhyun113** [HICURE/HICURE#35]
### 작업 사항💡

- AlarmList페이지의 버튼 클릭 시, 알람 편집 페이지로 이동하도록 만들기
- 색깔에 따라 편집 페이지 색상 다르게 구현
- 알람 시간 설정에 따라 저장하면 AlarmList에도 반영되도록 하기
- 알람 이름 텍스트 필드에 텍스트 입력 후, 저장 버튼 클릭 시, AlarmList에도 반영되도록 하기

### Todo

- [x] 색깔별, 버튼 클릭 시, 알람 편집 페이지로 이동 기능 구현
- [x] 알람 편집 페이지 UI 완성
- [x] 시간 정하는 토글? 기능 구현
- [x] 알람 이름 텍스트 필드 구현
- [x] 소리 및 진동 토글 버튼 및 클릭 기능 구현
- [x] 취소 버튼 클릭 시, 현재까지 변경한 사항 저장x 구현
- [ ] 저장 버튼 클릭 시, 알람 시간, 알람 이름, 소리 및 진동 변화 반영되도록 구현

### 기타사항

- 알람 기능 구현하면서, AlarmList 페이지의 텍스트 부분 변경에 따라 바뀌도록 하기
- 토글 버튼 크기 매우 작음 오류 해결 필요(당장은 안 해도 돼)
- AppBar 디자인 오류 해결 필요
- 하단 바 추가(현주 완성 시)
