### ISSUE TITLE
[FEATURE] BLE connect test

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#44]
### 작업 사항💡

현주 BLE하는거 도와주기!

### Todo

BLE와 연결하기
---
- [x] BLE 연동
- [x] BLE 주변 기기 보이기
- [x] BLE 연결
- [x] BLE 데이터 전달
- [x] BLE 데이터 받기

앱에서 데이터 처리하기
---
- [x] 3초 대기화면 만들기
- [x] 이후에 측정 시작하면 값들 보여줄 수 있게 만들기
- [x] 가장 큰 값 ( 가능하면 그래프로 ) 데이터 DB에 저장하기

### 기타사항

[BLE 참고 사이트](https://naver.me/FvEeAEsi)

BLE에 필요한 권한 및 설정
---
- 블루투스 ( 켜져있는지 확인 )
- 위치 권한 ( 알람, 근처 기기는 필요없음 )
