### ISSUE TITLE
[FEATURE] ServeInfo

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#57]
### 작업 사항💡

마무리 안된 serve info 만들기
---

Design
---
- [x] card 형식으로 데이터 보여주기
- [x] 내부 페이지 형식 만들기

Programming
---
- [x] 리사이클러뷰로 형태 변경
- [x] 오늘 이걸 봤는지 안 봤는지 체크
- [x] 하루에 본 것들 위주로 1점 추가

들어갈 자료
![image](https://github.com/user-attachments/assets/4fd58f97-07aa-48f1-b6bb-6fd31905fdff)

### Todo

- [x] 봤던거면 약간 색깔 다르게 하고 싶음 (sharedPrefernces로)
- [x] 일단 최대한 빨리
