### ISSUE TITLE
[FEATURE] Measume Data

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#64]
### 작업 사항💡

얻어진 데이터를 확실하게 보여주고, 좋고, 중간, 나쁨을 보여줘야합니다.

### Todo

- [x] 결과의 max값 추출
- [x] 사용자에 맞춰서 기준값 넣기
- [x] 사용자 기준값에 따라 max값을 상(+50), 중, 하(-100)로 상태 나눔
- [x] 결과값에 따라 score에 값 더하기
- [x] 저장한 데이터 그래프로 불러오기
- [x] ~하루 총 3회 측정할 수 있도록 제한 걸기~ ( 제한은 그냥 없앴음 )

### 기타사항
시간 남으면 하면 되는 것들
---
- [x] ~상, 중, 하를 이미지로 좋고 나쁨 표시~ (시간 애매함)
- [x] 전체적인 디자인 통일 ( 확인 )
- [x] 로그아웃할 수 있도록 하기

**Comment by gjsk132** [comment]
- [x] 사용자 키 추가
