### ISSUE TITLE
[FIX] 오류 수정

### ISSUE THREAD

**Issue by gjsk132** [HICURE/HICURE#70]
### 충돌 및 수정

추가로 발생한 오류들 수정

### Todo

- [x] 캘린더랑 메인 부분에서 충돌난거 확인하기
- [x] 알람 화면으로 넘어갔을 때, 하단 네비게이션바 고장나는거 수정하기
- [x] 만족도 조사 키 질문 없애기
- [x] 시작할 때 정확한 위치 정보를 제공할 때, 글씨 edge_blue인거 하얀색으로 바꾸기
- [x] 알람 하단바에 그림자 표현 ( 가능하면 )
- [x] 앱 프로필 이미지 만들어서 설정하기

### 기타사항

찐막
